# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQmrmbfO0Ghu8EhQ4lIapXmzKVk21-KT
"""

!pip install xgboost joblib seaborn

!wget https://raw.githubusercontent.com/plotly/datasets/master/heart.csv

import os
print(os.listdir())

from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = data.target

print(df.head())
print(df.shape)

import pandas as pd

diabetes_url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

cols = [
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age",
    "Outcome"
]

diabetes_df = pd.read_csv(
    diabetes_url,
    names=cols
)

print(diabetes_df.head())

import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

heart_df = pd.read_csv(url, header=None)

print(heart_df.head())

print(df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

df = df.drop_duplicates()

print(df.info())

import seaborn as sns
import matplotlib.pyplot as plt

def perform_eda(df, target):

    print(df.info())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicates:", df.duplicated().sum())

    plt.figure(figsize=(6,4))
    sns.countplot(data=df, x=target)
    plt.title(f"Distribution of {target}")
    plt.show()

from sklearn.datasets import load_breast_cancer
import pandas as pd

bc = load_breast_cancer()

breast_df = pd.DataFrame(
    bc.data,
    columns=bc.feature_names
)

breast_df["target"] = bc.target

print(breast_df.head())
print(breast_df.shape)

print("Heart:")
print(heart_df.columns.tolist())

print("\nDiabetes:")
print(diabetes_df.columns.tolist())

print("\nBreast:")
print(breast_df.columns.tolist())

print("\nHeart Shape:", heart_df.shape)
print("Diabetes Shape:", diabetes_df.shape)
print("Breast Shape:", breast_df.shape)

import matplotlib.pyplot as plt

def perform_eda(df, target):

    print(df.info())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicates:", df.duplicated().sum())

    plt.figure(figsize=(6,4))
    df[target].value_counts().plot(kind="bar")
    plt.title(f"Distribution of {target}")
    plt.show()

print(heart_df.columns.tolist())
heart_df.head()

print(heart_df.columns)

heart_df[13].value_counts().plot(kind="bar")
plt.title("Heart Disease Distribution")
plt.show()

perform_eda(diabetes_df, "Outcome")
perform_eda(breast_df, "target")

correlation = df.corr()['target'].sort_values(ascending=False)

print(correlation)

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df['mean radius'], bins=20)

plt.title("Distribution of Mean Radius")
plt.show()

heart_df.columns = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "target"
]

print(heart_df.columns)

print(heart_df["target"].head())

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

def train_models(X, y):

    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42
    )

    models = {
        "Logistic Regression": LogisticRegression(max_iter=5000),
        "SVM": SVC(),
        "Random Forest": RandomForestClassifier(),
        "XGBoost": XGBClassifier()
    }

    best_model = None
    best_score = 0

    for name, model in models.items():

        model.fit(X_train, y_train)

        pred = model.predict(X_test)

        acc = accuracy_score(y_test, pred)

        print(name, ":", round(acc*100,2), "%")

        if acc > best_score:
            best_score = acc
            best_model = model

    print("\nBest Accuracy:", round(best_score*100,2), "%")

    return best_model

import numpy as np

heart_df = heart_df.replace("?", np.nan)
heart_df = heart_df.apply(pd.to_numeric, errors='coerce')
print(heart_df.isna().sum())
heart_df = heart_df.fillna(heart_df.median())

X = heart_df.drop(columns=["target"])
y = heart_df["target"]

heart_model = train_models(X, y)

X = diabetes_df.drop("Outcome", axis=1)
y = diabetes_df["Outcome"]

diabetes_model = train_models(X, y)

X = breast_df.drop("target", axis=1)
y = breast_df["target"]

breast_model = train_models(X, y)

import joblib

joblib.dump(heart_model, "heart_model.pkl")
joblib.dump(diabetes_model, "diabetes_model.pkl")
joblib.dump(breast_model, "breast_model.pkl")

print("All models saved successfully!")

!pip install streamlit

import streamlit as st
import joblib
import numpy as np

st.set_page_config(
    page_title="Multi Disease Prediction System",
    page_icon="🩺",
    layout="wide"
)

st.title("🩺 Multi Disease Prediction System")

disease = st.selectbox(
    "Select Disease",
    [
        "Heart Disease",
        "Diabetes",
        "Breast Cancer"
    ]
)

# ---------------- HEART DISEASE ---------------- #

if disease == "Heart Disease":

    model = joblib.load("heart_model.pkl")

    st.subheader("❤️ Heart Disease Prediction")

    age = st.number_input("Age", 0, 120, 50)
    sex = st.number_input("Sex (0=Female, 1=Male)", 0, 1, 1)
    cp = st.number_input("Chest Pain Type", 0, 3, 0)
    trestbps = st.number_input("Resting Blood Pressure", 80, 250, 120)
    chol = st.number_input("Cholesterol", 100, 600, 200)
    fbs = st.number_input("Fasting Blood Sugar", 0, 1, 0)
    restecg = st.number_input("Rest ECG", 0, 2, 0)
    thalach = st.number_input("Max Heart Rate", 50, 250, 150)
    exang = st.number_input("Exercise Induced Angina", 0, 1, 0)
    oldpeak = st.number_input("Oldpeak", 0.0, 10.0, 1.0)
    slope = st.number_input("Slope", 0, 2, 1)
    ca = st.number_input("CA", 0, 4, 0)
    thal = st.number_input("Thal", 0, 3, 1)

    if st.button("Predict Heart Disease"):

        features = np.array([[
            age, sex, cp, trestbps, chol,
            fbs, restecg, thalach,
            exang, oldpeak, slope,
            ca, thal
        ]])

        prediction = model.predict(features)

        if prediction[0] == 1:
            st.error("⚠️ Heart Disease Detected")
        else:
            st.success("✅ No Heart Disease Detected")

# ---------------- DIABETES ---------------- #

elif disease == "Diabetes":

    model = joblib.load("diabetes_model.pkl")

    st.subheader("🩸 Diabetes Prediction")

    pregnancies = st.number_input("Pregnancies", 0, 20, 1)
    glucose = st.number_input("Glucose", 0, 300, 120)
    bp = st.number_input("Blood Pressure", 0, 200, 70)
    skin = st.number_input("Skin Thickness", 0, 100, 20)
    insulin = st.number_input("Insulin", 0, 1000, 80)
    bmi = st.number_input("BMI", 0.0, 70.0, 25.0)
    dpf = st.number_input("Diabetes Pedigree Function", 0.0, 3.0, 0.5)
    age = st.number_input("Age", 0, 120, 30)

    if st.button("Predict Diabetes"):

        features = np.array([[
            pregnancies,
            glucose,
            bp,
            skin,
            insulin,
            bmi,
            dpf,
            age
        ]])

        prediction = model.predict(features)

        if prediction[0] == 1:
            st.error("⚠️ Diabetes Detected")
        else:
            st.success("✅ No Diabetes Detected")

# ---------------- BREAST CANCER ---------------- #

else:

    model = joblib.load("breast_model.pkl")

    st.subheader("🎗️ Breast Cancer Prediction")

    radius = st.number_input("Mean Radius", value=14.0)
    texture = st.number_input("Mean Texture", value=20.0)
    perimeter = st.number_input("Mean Perimeter", value=90.0)
    area = st.number_input("Mean Area", value=600.0)

    smoothness = st.number_input("Mean Smoothness", value=0.1)
    compactness = st.number_input("Mean Compactness", value=0.1)
    concavity = st.number_input("Mean Concavity", value=0.1)
    concave_points = st.number_input("Mean Concave Points", value=0.05)

    if st.button("Predict Breast Cancer"):

        features = [0] * 30

        features[0] = radius
        features[1] = texture
        features[2] = perimeter
        features[3] = area
        features[4] = smoothness
        features[5] = compactness
        features[6] = concavity
        features[7] = concave_points

        prediction = model.predict([features])

        if prediction[0] == 1:
            st.success("✅ Benign Tumor")
        else:
            st.error("⚠️ Malignant Tumor")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.title("🩺 Multi Disease Prediction System")

from google.colab import files
files.download("app.py")

from google.colab import files

files.download("heart_model.pkl")
files.download("diabetes_model.pkl")
files.download("breast_model.pkl")
files.download("app.py")

!ls

